modLoader="javafml"

loaderVersion="[2,)"

license="MIT License"

[[mods]] #mandatory

modId="fastsuite"

version="6.0.7"

displayName="Fast Suite"

authors="Shadows_of_Fire"

description='''Introduces multithreading to the json recipe system.'''

[[mixins]]
config="fastsuite.mixins.json"

[[dependencies.fastsuite]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.fastsuite]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.187,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.fastsuite]]
    modId="placebo"
    type="required"
    versionRange="[9.9.0,)"
    ordering="AFTER"
    side="BOTH"
