modLoader="javafml"

loaderVersion="[2,)"

license="MIT License"

[[mods]] #mandatory

modId="fastsuite"

version="7.0.0"

displayName="Fast Suite"

authors="Shadows_of_Fire"

description='''Introduces multithreading to the json recipe system.'''

[[mixins]]
config="fastsuite.mixins.json"

[[dependencies.fastsuite]]
    modId="minecraft"
    type="required"
    versionRange="[26.1.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.fastsuite]]
    modId="neoforge"
    type="required"
    versionRange="[26.1.2.76,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.fastsuite]]
    modId="placebo"
    type="required"
    versionRange="[10.0.1,)"
    ordering="AFTER"
    side="BOTH"
